baseURL = "https://alexniver.github.io"
languageCode = "zh-cmn-Hans"
defaultContentLanguage = "zh"
title = "alexniver's blog"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = ""

disqusShortname = "alexniver"

enableRobotsTXT = true

hasCJKLanguage = true

[params]
  author = "alexniver"
  description = "alexniver's blog"
  avatar = "/img/head.jpg"
  motto = "你他娘的意大利炮呢？！"
  
  email = "zhulin10541@gmail.com"
  github = "alexniver"
  linkedin = "alexniver"
  codepen = "alexniver"
  stackoverflow = "1275503/alexniver"

  paginate = 4
  siteStartYear = 2019

  favicon = "/favicon.ico"
