baseURL = "https://alexniver.github.io/blog"
languageCode = "en-us"
title = "alexniver's blog"
description = "alexniver's blog"
canonifyURLs = true

theme = "capsule"
editor = "vim"
SectionPagesMenu = "main"
enableRobotsTXT = true
enableGitInfo = true
pygmentsstyle = "tango"
PygmentsCodeFences = true

[author]
  name = "alexniver"
  email = "zhulin10541@gmail.com"

[social]
  github = "alexniver"
  gitlab = "alexniver"

[params]
  repo = "https://github.com/alexniver/blog"
  share = true
  searchURL = "https://duckduckgo.com"
  related = "all"
